#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     

bspc config border_width         4
bspc config window_gap           0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#ff373B41"
bspc config normal_border_color "#ff000000"

bspc rule -a Ulauncher border=off
bspc rule -a TelegramDesktop desktop=

picom &
killall -q polybar
~/.config/polybar/launch.sh
feh --bg-scale ~/Pictures/wallpaper.jpg
killall -q ulauncher
ulauncher &
$HOME/Software/Telegram/Telegram
xinput set-prop 11 300 1 # Natural Scrolling
xinput set-prop 11 323 1 # Tapping
