#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d         

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           0

bspc config focused_border_color "#303030"
bspc config normal_border_color "#101010"

bspc rule -a Ulauncher border=off
bspc rule -a TelegramDesktop desktop=

picom &
killall -q polybar
~/.config/polybar/launch.sh
feh --bg-scale ~/Pictures/wallpaper.jpg
killall -q ulauncher
ulauncher &
nm-applet &
blueman-applet &
$HOME/Software/Telegram/Telegram
xinput set-prop 11 300 1 # Natural Scrolling
xinput set-prop 11 323 1 # Tapping
