#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         4
bspc config window_gap           0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#a19959"
bspc config normal_border_color "#000000"

bspc rule -a Ulauncher border=off

picom &
killall -q polybar
polybar &
feh --bg-scale ~/Pictures/wallpaper.jpg
killall -q ulauncher
ulauncher &
xinput set-prop 11 300 1 # Natural Scrolling
xinput set-prop 11 323 1 # Tapping
